import Redis from "ioredis";
import { BaseConfig } from "../../config/BaseConfig";
import { BaseService } from "../../core/BaseService";
import { OrganizationService } from "./module/organization.service";
import { PatientService } from "./module/patient.service";
import { LocationService } from "./module/location.service";
import { PractisionerService } from "./module/practisioner.service";
import { EncounterService } from "./module/encounter.service";
import { ConditionService } from "./module/condition.service";
import { ObservationService } from "./module/observation.service";
import { CompositionService } from "./module/composition.service";
import { ProcedureService } from "./module/procedure.service";
import { MedicationService } from "./module/medication.service";
import { MedicationRequestService } from "./module/medicationRequest.service";
import { MedicationDispenseService } from "./module/medicationDispense.service";
import { DiagnosticReportService } from "./module/diagnosticReport.service";
import { AllergyIntoleranceService } from "./module/allergyIntolerance.service";
import { ClinicalImpressionService } from "./module/clinicalImpression.service";
import { ImmunizationService } from "./module/immunization.service";
import { ImagingStudyService } from "./module/imagingStudy.service";
import { EpisodeOfCareService } from "./module/episodeOfCare.service";
import { CarePlanService } from "./module/carePlan.service";
import { QuestionnaireResponseService } from "./module/questionnaireResponse.service";
import { ServiceRequestService } from "./module/serviceRequest.service";
import { SpecimenService } from "./module/specimen.service";
import { RelatedPersonService } from "./module/relatedPerson.service";
import { CoverageService } from "./module/coverage.service";
import { CoverageEligibilityRequestService } from "./module/coverageEligibilityRequest.service";
import { CoverageEligibilityResponseService } from "./module/coverageEligibilityResponse.service";
import { AccountService } from "./module/account.service";
import { ChargeItemService } from "./module/chargeItem.service";
import { InvoiceService } from "./module/invoice.service";
import { ClaimService } from "./module/claim.service";
import { ClaimResponseService } from "./module/claimResponse.service";
import { PaymentReconciliationService } from "./module/paymentReconciliation.service";
import { PaymentNoticeService } from "./module/paymentNotice.service";

export class ResourceService extends BaseService {
  readonly organization!: OrganizationService;
  readonly patient!: PatientService;
  readonly location!: LocationService;
  readonly practisioner!: PractisionerService;
  readonly encounter!: EncounterService;
  readonly condition!: ConditionService;
  readonly observation!: ObservationService;
  readonly composition!: CompositionService;
  readonly procedure!: ProcedureService;
  readonly medication!: MedicationService;
  readonly medicationRequest!: MedicationRequestService;
  readonly medicationDispense!: MedicationDispenseService;
  readonly diagnosticReport!: DiagnosticReportService;
  readonly allergyIntolerance!: AllergyIntoleranceService;
  readonly clinicalImpression!: ClinicalImpressionService;
  readonly immunization!: ImmunizationService;
  readonly imagingStudy!: ImagingStudyService;
  readonly episodeOfCare!: EpisodeOfCareService;
  readonly carePlan!: CarePlanService;
  readonly questionnaireResponse!: QuestionnaireResponseService;
  readonly serviceRequest!: ServiceRequestService;
  readonly specimen!: SpecimenService;
  readonly relatedPerson!: RelatedPersonService;
  readonly coverage!: CoverageService;
  readonly coverageEligibilityRequest!: CoverageEligibilityRequestService;
  readonly coverageEligibilityResponse!: CoverageEligibilityResponseService;
  readonly account!: AccountService;
  readonly chargeItem!: ChargeItemService;
  readonly invoice!: InvoiceService;
  readonly claim!: ClaimService;
  readonly claimResponse!: ClaimResponseService;
  readonly paymentReconciliation!: PaymentReconciliationService;
  readonly paymentNotice!: PaymentNoticeService;

  constructor(config: BaseConfig, redisClient: Redis) {
    super(config, redisClient);

    this.organization = new OrganizationService(this);
    this.patient = new PatientService(this);
    this.location = new LocationService(this);
    this.practisioner = new PractisionerService(this);
    this.encounter = new EncounterService(this);
    this.condition = new ConditionService(this);
    this.observation = new ObservationService(this);
    this.composition = new CompositionService(this);
    this.procedure = new ProcedureService(this);
    this.medication = new MedicationService(this);
    this.medicationRequest = new MedicationRequestService(this);
    this.medicationDispense = new MedicationDispenseService(this);
    this.diagnosticReport = new DiagnosticReportService(this);
    this.allergyIntolerance = new AllergyIntoleranceService(this);
    this.clinicalImpression = new ClinicalImpressionService(this);
    this.immunization = new ImmunizationService(this);
    this.imagingStudy = new ImagingStudyService(this);
    this.episodeOfCare = new EpisodeOfCareService(this);
    this.carePlan = new CarePlanService(this);
    this.questionnaireResponse = new QuestionnaireResponseService(this);
    this.serviceRequest = new ServiceRequestService(this);
    this.specimen = new SpecimenService(this);
    this.relatedPerson = new RelatedPersonService(this);
    this.coverage = new CoverageService(this);
    this.coverageEligibilityRequest = new CoverageEligibilityRequestService(this);
    this.coverageEligibilityResponse = new CoverageEligibilityResponseService(this);
    this.account = new AccountService(this);
    this.chargeItem = new ChargeItemService(this);
    this.invoice = new InvoiceService(this);
    this.claim = new ClaimService(this);
    this.claimResponse = new ClaimResponseService(this);
    this.paymentReconciliation = new PaymentReconciliationService(this);
    this.paymentNotice = new PaymentNoticeService(this);
  }
}
